### ISSUE TITLE
Character Error while outline in illustrator

### ISSUE THREAD

**Issue by aravind-roy** [smc/Rachana#2]
ഞ്ഞ letter displays wrong when converted to outline. Issue only occurs in illustrator. Illustrator v. 28.0

![Screenshot (55)](https://github.com/smc/Rachana/assets/40258924/1e91fadc-cfbb-4455-9374-a6ade3f82640)

**Comment by tachyons** [comment]
Development of this project is moved to the fork https://gitlab.com/rit-fonts/RIT-Rachana

**Comment by aravind-roy** [comment]
Issue cleared in v.1.4.7
